FROM vikingco/python:{{ pythonversion }}
LABEL maintainer="technology@unleashed.be"

#############################
# Set environment variables #
#############################
ENV PYENV_VERSION={{ pythonversion }} \
    CONF_SRC=./conf \
    CONF_DIR=${ROOT}/conf \
    RUN_DIR=${ROOT}/run \
    MEDIA_ROOT=${ROOT}/media \
    STATIC_ROOT=${ROOT}/static \
    MANAGE_FILE=manage.py \
    DJANGO_ROOT=${SRC_DIR} \
    WSGI_FILE=wsgi.py \
    PYTHON_PATH=${SRC_DIR}:${PYENV_ROOT}/versions/{{ pythonversion }}/bin

########################
# Configure build args #
########################
ARG PORT=8000
ARG UWSGI_PORT=3031
ARG STATUS_PORT=9191
ENV PORT=${PORT} \
    UWSGI_PORT=${UWSGI_PORT} \
    STATUS_PORT=${STATUS_PORT}

##############################
# Copy deployment into image #
##############################
COPY ${DEPLOYMENT_SRC} ${DEPLOYMENT_DIR}

#####################################
# Install packages and requirements #
#####################################
RUN set -x \
    && buildPackages=`cat ${DEPLOYMENT_DIR}/${REQUIRED_BUILD_PACKAGES_FILE}` \
    && runtimePackages=`cat ${DEPLOYMENT_DIR}/${REQUIRED_RUNTIME_PACKAGES_FILE}` \
    && yum install -y ${runtimePackages} ${buildPackages} \
    && pip install -r ${DEPLOYMENT_DIR}/${PYTHON_REQUIREMENTS_FILE} \
    && find ${PYENV_ROOT} \
		\( -type d -a -name test -o -name tests \) \
		-o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
		-exec rm -rf '{}' + \
    && rm -rf /tmp/* \
    && yum remove -y ${buildPackages} \
    && yum clean all

####################
# Make directories #
####################
RUN mkdir -p ${MEDIA_ROOT} && \
    mkdir -p ${STATIC_ROOT} && \
    mkdir -p ${RUN_DIR}

#################
# Copy in files #
#################
COPY ${CONF_SRC} ${CONF_DIR}
COPY ${SCRIPTS_SRC} ${SCRIPTS_DIR}

################
# Expose ports #
################
EXPOSE ${PORT} ${STATUS_PORT} ${UWSGI_PORT}

###############
# Set workdir #
###############
WORKDIR ${DJANGO_ROOT}
